# Generated by Django 5.2.4 on 2025-07-15 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_transaction_customer_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='customer_id',
            field=models.UUIDField(),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='product_id',
            field=models.UUIDField(),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='timestamp',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_id',
            field=models.UUIDField(primary_key=True, serialize=False),
        ),
    ]
